### NUMPY

In [736]:
import numpy as np


In [737]:
type([list])

#jadi
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [738]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [739]:
#untuk tau ini termasuk tipe apa
print(type(a))

<class 'numpy.ndarray'>


In [740]:
[[1, 2, 3, 4], 
 [5, 6, 7, 8], 
 [9, 10, 11, 12]] #ada 3 baris dan 4 kolom

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [741]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [742]:
print(a.ndim) #untuk tau ada berapa dimensi

2


In [743]:
print(a.shape) #untuk tau ada berapa jumlah komponen di dimensinya

(3, 4)


In [744]:
a[1]

array([5, 6, 7, 8])

In [745]:
a[1][2]

7

In [746]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [747]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [748]:
#berikut ada 1 dimensi, 5 komponen
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [749]:
#berikut ada 2 dimensi, 5 komponen
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [750]:
#berikut ada 3 dimensi, 2 komponen
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

code di atas ada 3 dimensi (diliat dari jumlah kurung sikunya)

In [751]:
np.empty((2,2))

array([[3.5e-323, 4.0e-323],
       [4.4e-323, 4.9e-323]])

In [752]:
range(5)

range(0, 5)

In [753]:
list(range(5))

[0, 1, 2, 3, 4]

In [754]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [755]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [756]:
np.arange(2, 10, 2)

#penjelasannya
# np.arange(angka awal, angka maksimal tapi gaketulis, jumlah longkap)

array([2, 4, 6, 8])

In [757]:
a_list = list(range(10))
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [758]:
a_list.append(list(range(3)))

In [759]:
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, [0, 1, 2]]

In [760]:
for i in range(3):
    a_list.append(i)

print(a_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, [0, 1, 2], 0, 1, 2]


In [761]:
np.append(range(10), range(3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [762]:
a_numpy = np.arange(10)
a_numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [763]:
np.append(a_numpy, range(3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [764]:
np.append(a_numpy, np.arange(3).reshape(3,1))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

#axis=0 jadi baris

#axis=1 jadi kolom

In [765]:
#kalo axis 0 bebas, boleh gak sama jumlah dimensi di dalem kurung sikunya
#axis 0 hasilnya ke bawah

np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [766]:
#acontoh kalo gasama jumlah di kurung sikunya, tetep bisa muncul hasil printnya
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [767]:
#acontoh kalo gasama dimensinya, jadi error
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9, 10]], axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [768]:
#kalo axis 1 harus sama semuanya jumlah di dalem masing2 kurung siku karna
#axis 1 hasilnya ke samping

np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [769]:
#contoh kalo gasama jumlah di dalem masing2 kurung sikunya, bakalan jadi error
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [770]:
#kalo gapake axis tetep bisa 
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [771]:
np.append([[1, 2, 3]], [[4, 5, 6]], axis=1)

array([[1, 2, 3, 4, 5, 6]])

In [772]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [773]:
np.array([7, 8, 9])

array([7, 8, 9])

In [774]:
#kalo mau digabung jadinya:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#axis=0 baris
#axis=1 kolom

In [775]:
a_list = list(range(10))
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [776]:
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [777]:
for i in range(3):
    a_list.append(i)

print(a_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2]


In [778]:
#atau bisa pake cara ini biar lebih cepet
np.append(range(10), range(3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [779]:
#berikut ada 2 kolom, 5 baris
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [780]:
#berikut ada 3 kolom, 1 baris
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [781]:
#berikut ada 3 baris dan 1 kolom
np.arange(3).reshape(1, 3)

array([[0, 1, 2]])

### DELETE

In [782]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [783]:
#CATATAN

#array([[ 1,  2,  3,  4], #1 baris indeks ke-0
       #[ 5,  6,  7,  8], #1 baris indeks ke-1
       #[ 9, 10, 11, 12]]) #1 baris indeks ke-2

In [784]:
#axis 0 nambah baris
#axis 1 nambah kolom

In [785]:
#cara menghapus indeks ke-1
np.delete(a, 1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#CATATAN

np.delete(a, baris, kolom)

- baris itu ke samping
- kolom itu ke bawah


In [786]:
#menghapus 1 baris indeks ke-1
np.delete(a, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [787]:
#menghapus 1 kolom indeks ke-1
np.delete(a, 1, 1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [788]:
#menghapus 1 barisan indeks ke-2
np.delete(a, 2, 0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [789]:
#menghapus 1 kolom di indeks ke-2
np.delete(a, 2, 1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

- axis=0 baris
- axis= 1 kolom

In [790]:
#buat menghapus baris paling terakhir
np.delete(a, -1, axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### SORT

In [791]:
np.append(range(52,55), range(21,27))

array([52, 53, 54, 21, 22, 23, 24, 25, 26])

kalo code di atas mau diurutin jadinya:

In [792]:
b_sort = np.append(range(52,55), range(21,27))

In [793]:
np.sort(b_sort)

array([21, 22, 23, 24, 25, 26, 52, 53, 54])

### MENGETAHUI ANALISA DATA KITA SEPERTI APA:

In [794]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [795]:
#untuk mengetahui jumlah baris dan kolom
print(a.shape)

(3, 4)


jadi ada 3 baris, 4 kolom

In [796]:
#untuk mengetahui ada brp dimensi
print(a.ndim)

2


In [797]:
#untuk mengetahui ada brp elemen
print(a.size)

12


### RESHAPE

In [798]:
a.reshape(1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [799]:
#error karna size/elemen kita ada 12
a.reshape(2, 5)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [800]:
a.reshape (3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [801]:
a.reshape (1, 2, 6)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]])

In [802]:
a.reshape (4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [803]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [804]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [805]:
np.arange(20).reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [806]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [807]:
a[np.newaxis]

array([[0, 1, 2, 3, 4]])

In [808]:
a[np.newaxis, :]

array([[0, 1, 2, 3, 4]])

In [809]:
a[np.newaxis].shape

(1, 5)

In [810]:
#menambahkan jumlah kolom
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

cara menghadirkan penjelasan dari fungsi, bisa pake

help(np.array)

In [811]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

### EXPAND/MENAMBAHKAN

In [812]:
a

array([0, 1, 2, 3, 4])

In [813]:
#menambahkan dengan axis sebagai function
np.expand_dims(a, axis=1).shape

(5, 1)

### INDEXING SLICING

In [814]:
a = np.array([0, 1, 2, 3, 4, 5])
a

array([0, 1, 2, 3, 4, 5])

In [815]:
a[0]

0

In [816]:
#mulai dari 0
a[0:3]

array([0, 1, 2])

In [817]:
#akan keluar hasil semua angka
a[:]

array([0, 1, 2, 3, 4, 5])

In [818]:
a[-3:]

array([3, 4, 5])

In [819]:
a[:-1]

array([0, 1, 2, 3, 4])

In [820]:
a > 2

array([False, False, False,  True,  True,  True])

In [821]:
a > 3

array([False, False, False, False,  True,  True])

In [822]:
#jika a>3, maka[np.array([0, 1, 2, 3, 4, 5])

a[np.array([False, False, False, True, True, True])
]

array([3, 4, 5])

In [823]:
a > 2

array([False, False, False,  True,  True,  True])

In [824]:
a[np.array([False, False, True,  True, False,   True])]

array([2, 3, 5])

In [825]:
a[a > 2]

array([3, 4, 5])

In [826]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [827]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11])

In [828]:
above_five = a > 8

In [829]:
a[above_five]

array([ 9, 10, 11])

In [ ]:
True false

In [ ]:
==
>=
<=
>
<

In [831]:
a * 5

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [832]:
a * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [833]:
#listnya diulang 2x
a_list * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2]

In [834]:
a % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [835]:
#hasil persentasenya sama dengan 0 = true
a % 2 == 0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [836]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [837]:
genap = a % 2 == 0

a[genap]

array([ 0,  2,  4,  6,  8, 10])

In [838]:
a[(a > 2) & (a < 11) & (a % 2 != 0)]

array([3, 5, 7, 9])

In [839]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [840]:
np.arange(2)

array([0, 1])

In [841]:
np.arange(1, 3)

array([1, 2])

In [842]:
a_1 = np.append([[1, 1]], [[2, 2]], axis=0)
a_1

array([[1, 1],
       [2, 2]])

In [843]:
a_1 = np.array([[1, 1],
                [2, 2]])
a_2 = np.array([[3, 3],
                [4, 4]])

In [844]:
np.append(a_1, a_2, axis =0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [845]:
#ATAU
np.vstack([a_1, a_2]) #append axis 0

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [846]:
np.append(a_1, a_2, axis =1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [847]:
#ATAU
np.hstack([a_1, a_2]) #append axis 1

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

### SPLIT/DIPECAH

In [848]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [849]:
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [850]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [851]:
list(range(10, 100, 5))

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [852]:
#ATAU 
tuple(range(10, 100, 5))

(10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95)

In [853]:
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [854]:
#kalo dipecah/displit jadi 3 
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [855]:
#untuk tau jenis tipe datanya
type(np.hsplit(arrsplit, 3))

list

In [856]:
for i in np.hsplit(arrsplit, 3):
    print(i)

[[ 1  2  3  4]
 [13 14 15 16]]
[[ 5  6  7  8]
 [17 18 19 20]]
[[ 9 10 11 12]
 [21 22 23 24]]


In [857]:
#cara pecah data jadi horizontal dalam 3 kolom
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [858]:
#cara pecah data jadi horizontal dalam 12 kolom
np.hsplit(arrsplit, 12)

[array([[ 1],
        [13]]),
 array([[ 2],
        [14]]),
 array([[ 3],
        [15]]),
 array([[ 4],
        [16]]),
 array([[ 5],
        [17]]),
 array([[ 6],
        [18]]),
 array([[ 7],
        [19]]),
 array([[ 8],
        [20]]),
 array([[ 9],
        [21]]),
 array([[10],
        [22]]),
 array([[11],
        [23]]),
 array([[12],
        [24]])]

In [859]:
h_1, h_2, h_3 = np.hsplit(arrsplit, 3)

In [860]:
h_1

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [861]:
h_2

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [862]:
h_3

array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])

In [863]:
#cara pecah data jadi vertikal
np.vsplit(arrsplit, 2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

### STACK/SUSUN DATA

In [864]:
#cara susun data jadi horizontal
np.hstack([h_1, h_2, h_3])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [865]:
#cara susun data jadi vertikal
np.vstack([h_1, h_2, h_3])

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16],
       [ 5,  6,  7,  8],
       [17, 18, 19, 20],
       [ 9, 10, 11, 12],
       [21, 22, 23, 24]])

### VIEW

In [866]:
a.view()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [867]:
b = a

In [868]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [869]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [870]:
b[1][-1] = 100

In [871]:
b

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [872]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [873]:
#kenapa b diganti, a juga ikut keganti karna =
id(a) == id(b)

True

In [ ]:
#kan a = b, tapi kalo kita mau kotak katik a tanpa harus b keganti, maka bisa gunakan rumus:
c = a.view()

#ATAU
c = a.copy()

#ATAU
backup_dataframe = dataframe.copy()

### BASIC OPERATIONS

In [ ]:
+
-
/
*
%

#by element, bukan perkalian matriks

In [877]:
a + 5

array([[  5,   6,   7,   8],
       [  9,  10,  11, 105],
       [ 13,  14,  15,  16]])

In [878]:
a - 5

array([[-5, -4, -3, -2],
       [-1,  0,  1, 95],
       [ 3,  4,  5,  6]])

In [879]:
a * 3

array([[  0,   3,   6,   9],
       [ 12,  15,  18, 300],
       [ 24,  27,  30,  33]])

In [880]:
a / 6

array([[ 0.        ,  0.16666667,  0.33333333,  0.5       ],
       [ 0.66666667,  0.83333333,  1.        , 16.66666667],
       [ 1.33333333,  1.5       ,  1.66666667,  1.83333333]])

In [881]:
a % 3

array([[0, 1, 2, 0],
       [1, 2, 0, 1],
       [2, 0, 1, 2]])

In [882]:
a + 5 - 7 * 3 / 2

array([[-5.5, -4.5, -3.5, -2.5],
       [-1.5, -0.5,  0.5, 94.5],
       [ 2.5,  3.5,  4.5,  5.5]])

In [883]:
a + a

array([[  0,   2,   4,   6],
       [  8,  10,  12, 200],
       [ 16,  18,  20,  22]])

In [884]:
a * a

array([[    0,     1,     4,     9],
       [   16,    25,    36, 10000],
       [   64,    81,   100,   121]])

In [885]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [886]:
np.ones(12).reshape(3, 4) * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [887]:
a * np.ones(12).reshape(3, 4) * 3

array([[  0.,   3.,   6.,   9.],
       [ 12.,  15.,  18., 300.],
       [ 24.,  27.,  30.,  33.]])

In [ ]:
#perkalian/dots matriks
a b         x       a b
c d                 c d

In [ ]:
a*a + b*c       a*b + b*c
c*a + d*c       c*b + d*d

In [890]:
#pake rumus berikut
np.dot

<function numpy.dot>

In [891]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(5).sum()

In [ ]:
np.sum(np.arange(5))

In [897]:
a.sum() # dengan method call

159

In [898]:
#ATAU
np.sum(a) #function call

159

In [899]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [ ]:
#RUMUS UMUM
np.sum() #total
np.absolute()
np.mean() #nilai tengah
np.median()
np.add() #penjumlahan
np.subtract()
np.nan #nilai kosong (not a number)
np.nansum() #sama kayak sum, tapi kalo ada kosong jadi 0


In [901]:
#contoh apabila ada nan tanpa menggunakan nansum
np.array([np.nan, 5]).sum()

nan

In [902]:
#tapi kalo menggunakan nansum
np.nansum([np.nan, 5]).sum()

5.0

SIFAT SPESIAL NUMPY IDENTITY:
- kalo diperkalian *1, maka hasilnya matriks itu lagi


In [903]:
np.identity(1)

array([[1.]])

In [904]:
np.linspace(1, 4, num=4).reshape(2, 2)

array([[1., 2.],
       [3., 4.]])

In [905]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [906]:
np.linspace(1, 4, num=4).reshape(2, 2).dot(np.identity(2))

array([[1., 2.],
       [3., 4.]])

In [907]:
b = np.array([[1,1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [908]:
b.sum()

6

In [909]:
#kalo axis=0 barisnya yang dijumlahin
b.sum(axis=0)

array([3, 3])

In [910]:
#kalo axis=1 kolomnya yang dijumlahin
b.sum(axis=1)

array([2, 4])

In [911]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [912]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [913]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [914]:
x1 = np.linspace(5, 122, num=4).reshape(2, 2)
x2 = np.linspace(8, 32, num=4).reshape(2, 2)

In [915]:
x1

array([[  5.,  44.],
       [ 83., 122.]])

In [916]:
x2

array([[ 8., 16.],
       [24., 32.]])

In [917]:
x1 * x2

array([[  40.,  704.],
       [1992., 3904.]])

In [918]:
#sum dengan axis=0
np.sum([x1, x2], axis=0) 

array([[ 13.,  60.],
       [107., 154.]])

In [919]:
#sum dengan axis=1
np.sum([x1, x2], axis=1) 

array([[ 88., 166.],
       [ 32.,  48.]])

In [920]:
#product dengan axis=0
np.product([x1, x2], axis=0)

array([[  40.,  704.],
       [1992., 3904.]])

In [921]:
#product dengan axis=1
np.product([x1, x2], axis=1)

array([[ 415., 5368.],
       [ 192.,  512.]])

In [922]:
#mencari maksimum
np.maximum(x1, x2)

array([[  8.,  44.],
       [ 83., 122.]])

In [923]:
#mencari minimum
np.minimum(x1, x2)

array([[ 5., 16.],
       [24., 32.]])

In [924]:
#mencari minimum
np.min(x1)

5.0

In [925]:
#deviation dengan axis=0
np.std([x1, x2], axis=0)


array([[ 1.5, 14. ],
       [29.5, 45. ]])

In [926]:
#deviation dengan axis=1
np.std([x1, x2], axis=1)


array([[39., 39.],
       [ 8.,  8.]])

In [927]:
#apabila butuh data random
np.random.randint(1, 100, size=10)

array([59, 73, 39, 36, 50, 89, 35, 75, 11, 58])

In [928]:
#apabila butuh data random normal distribusi
d = np.random.randn(3, 4)

In [929]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [930]:
d

array([[ 0.4319641 ,  0.72656436, -0.5374814 ,  0.39157583],
       [-0.17355   , -0.38716061, -0.46862657, -0.46980689],
       [-0.87660592, -1.82912243, -0.97118801,  0.61298614]])

In [931]:
a * d

array([[  0.        ,   0.72656436,  -1.0749628 ,   1.1747275 ],
       [ -0.6942    ,  -1.93580307,  -2.81175945, -46.98068883],
       [ -7.0128474 , -16.46210183,  -9.71188009,   6.7428475 ]])